<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INW1PF1PY3M7" name="com.hellofresh.challenge.WebTest" tests="3" failures="0" timestamp="22 Jan 2020 18:12:01 GMT" time="614.048" errors="2">
  <testcase name="LogIntest" time="16.083" classname="com.hellofresh.challenge.WebTest"/>
  <testcase name="signInTest" time="543.434" classname="com.hellofresh.challenge.WebTest">
    <error type="java.lang.AssertionError" message="expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]">
      <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hellofresh.challenge.SignUpPage.SignInSuccessAsserts(SignUpPage.java:93)
	at com.hellofresh.challenge.WebTest.signInTest(WebTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- signInTest -->
  <testcase name="CheckOuttest" time="54.531" classname="com.hellofresh.challenge.WebTest">
    <error type="java.lang.AssertionError" message="expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]">
      <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hellofresh.challenge.CheckOutPage.checkoutTest(CheckOutPage.java:52)
	at com.hellofresh.challenge.WebTest.CheckOuttest(WebTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- CheckOuttest -->
</testsuite> <!-- com.hellofresh.challenge.WebTest -->
